name: e2e
on:
  pull_request:
  push:
    branches:
      - 'release-*'
      - 'master'
      - 'main'
    tags:
      - 'v*'
jobs:
  e2e-tests:
    continue-on-error: true
    name: E2E tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        suite: [prometheus]
        include:
          - suite: prometheus
            prometheus: ""
            prometheusAllNS: "exclude"
            alertmanager: "exclude"
            thanosruler: "exclude"
            operatorUpgrade: "exclude"
            featureGated: "include"
    steps:
    - uses: actions/checkout@v3
    - name: Import environment variables from file
      run: cat ".github/env" >> $GITHUB_ENV
    - name: Install Go
      uses: actions/setup-go@v4
      with:
        go-version: '${{ env.golang-version }}'
    - name: Build images
      run: |
        export SHELL=/bin/bash
        make build image
    - name: Start KinD
      uses: engineerd/setup-kind@v0.5.0
      with:
        version: ${{ env.kind-version }}
        image: ${{ env.kind-image }}
        config: /test/e2e/kind-conf.yaml
        wait: 300s
    - name: Setup upterm session
      if: ${{ failure() }}
      uses: lhotari/action-upterm@v1
      with:
        ## limits ssh access and adds the ssh public key for the user which triggered the workflow
        limit-access-to-actor: true
        ## limits ssh access and adds the ssh public keys of the listed GitHub users
        limit-access-to-users: philipgough
    - name: Wait for cluster to finish bootstraping
      run: |
        kubectl wait --for=condition=Ready pods --all --all-namespaces --timeout=300s
        kubectl cluster-info
        kubectl get pods -A
    - name: Load images
      run: |
        kind load docker-image quay.io/prometheus-operator/prometheus-operator:$(git rev-parse --short HEAD)
        kind load docker-image quay.io/prometheus-operator/prometheus-config-reloader:$(git rev-parse --short HEAD)
        kind load docker-image quay.io/prometheus-operator/admission-webhook:$(git rev-parse --short HEAD)
        kubectl apply -f scripts/kind-rbac.yaml
    - name: Run tests
      run: >
        EXCLUDE_ALERTMANAGER_TESTS=${{ matrix.alertmanager }}
        EXCLUDE_PROMETHEUS_TESTS=${{ matrix.prometheus }}
        EXCLUDE_PROMETHEUS_ALL_NS_TESTS=${{ matrix.prometheusAllNS }}
        EXCLUDE_THANOSRULER_TESTS=${{ matrix.thanosruler }}
        EXCLUDE_OPERATOR_UPGRADE_TESTS=${{ matrix.operatorUpgrade }}
        FEATURE_GATED_TESTS=${{ matrix.featureGated }}
        make test-e2e
